language: java
jdk:
  - oraclejdk8

before_deploy:
  - "mvn -DskipTests package"
  - export JAR_FILE=$(ls target/skeleton-cli-*.jar)

deploy:
  api_key:
    secret: ${GITHUB_PAT}
  provider: releases
  file: "${JAR_FILE}"
